---
title: "Body_Temp_COSINOR_Comp"
output: html_document
date: "2024-07-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Installing and Accessing Exterior Packages
library(tidyverse)
library(rstatix)
library(nloptr)
library(ggplot2)
library(cosinor)
library(cosinor2)
library(lubridate)
library(diffCircadian)
library(grid)
library(gridExtra)
library(gtable)
library(here)
library(dplyr)
```

#### Creating and Plotting the Cosinor Body Temp Model for LD Rat Data
```{r}
# Reading Body Temperature Information for LD Rats
readxl::read_excel(path ="../Circadian Disruption ZT Data.xlsx",
                   sheet = "Body Temperature",
                    range ="E1:F49") -> Circadian_BodyTemp_LD
```

```{r}
# Cleaning Up Data Column Headers for Easier Translation 
Circadian_BodyTemp_LD %>%
  rename(ZT = `Zeitgeber (ZT)`, 
         BodyTemp = `LD Body Temperature (degrees C)`) -> LD_Circadian_BodyTemp


# Creating Cosinor Model for LD Rats
cosinor.lm(BodyTemp ~ time(ZT), period = 24,
           data = LD_Circadian_BodyTemp) -> cosMod_LD
```

```{r}
# Creating Table of Data Values of Interest for LD Rat Model
## Isolating Coefficients in LD Cosinor Model
coef(cosMod_LD) -> LD_coefficients

# Indexing Unique/Important Coefficients for Table Storage
## Calculate Mesor
LD_coefficients[1] -> mesor_LD
## Calculate Amplitude
LD_coefficients[2] -> amplitude_LD
## Calculate Acrophase in Radians
LD_coefficients[3] -> acrophase_LD
## Calculate Acrophase in Hours
(acrophase_LD * 24) / (2 * pi) -> acrophase_LD_Hrs
if(acrophase_LD_Hrs < 0) {acrophase_LD_Hrs <- acrophase_LD_Hrs + 24}
# Calculate Bathyphase in Hours
acrophase_LD_Hrs + 12 -> bathyphase_LD_Hrs
if(bathyphase_LD_Hrs >= 24) {
  bathyphase_LD_Hrs <- bathyphase_LD_Hrs - 24}

# Calculating Number of Observations in Data Set
num_observations_LD <- length(cosMod_LD$fit$residuals)

# Manually Compute Standard Error
residuals_vec_LD <- cosMod_LD$fit$residuals
  
# Check residuals
#if (length(residuals_vec) == 0) {
#  stop("Residuals cannot be computed. The model may not be fit properly.")
#}
  
# Calculate residual standard error
residual_se_LD <- sqrt(sum(residuals_vec_LD^2) / (num_observations_LD - length(LD_coefficients)))
  
# Print residual standard error for debugging
#print(paste("Residual Standard Error:", residual_se))
  
# Calculate standard deviation and standard error of acrophase
sd_acrophase_LD <- residual_se_LD * sqrt((cos(acrophase_LD)^2 + sin(acrophase_LD)^2) / (amplitude_LD^2))
se_acrophase_LD <- sd_acrophase_LD / sqrt(num_observations_LD)
  
# Calculate standard deviation and standard error of acrophase
sd_acrophase_hrs_LD <- (sd_acrophase_LD * 24) / (2 * pi)
se_acrophase_hrs_LD <- (se_acrophase_LD * 24) / (2 * pi)
  
# Ensure all computed values are single values
sd_acrophase_LD <- as.numeric(sd_acrophase_LD)
se_acrophase_LD <- as.numeric(se_acrophase_LD)
sd_acrophase_hrs_LD <- as.numeric(sd_acrophase_hrs_LD)
se_acrophase_hrs_LD <- as.numeric(se_acrophase_hrs_LD)

# Creating Table to Store Unique/Important Coefficients
data.frame(Parameter = c("Mesor","Amplitude","Acrophase (Rads)",
                         "Acrophase (Hrs)", "Bathyphase (Hrs)",
                         " Std. Dev. (Rads)"," Std. Error (Rads)",
" Std. Dev (Hrs)", " Std. Error (Hrs)"), 
           Values =  c(mesor_LD, amplitude_LD, 
           acrophase_LD, acrophase_LD_Hrs, bathyphase_LD_Hrs,
           sd_acrophase_LD, se_acrophase_LD, sd_acrophase_hrs_LD, 
           se_acrophase_hrs_LD)) -> LD_Results

# Converting Table into a Graphical Object
tableGrob(LD_Results) -> LD_Results_grob
```

```{r}
# Zero-Amplitude Analysis of Cosinor Fit
cosinor.detect(cosMod_LD) -> zero_amp_test_LD

# Indexing Unique/Important Coefficients for Table Storage
## Calculate Df1
zero_amp_test_LD[2] -> df1_LD
## Calculate Df2
zero_amp_test_LD[3] -> df2_LD
## Calculate F Value
zero_amp_test_LD[1] -> fval_LD
## Calculate p Value
zero_amp_test_LD[4] -> pval_LD

#Improving Figure Literacy for Large Values
format(df1_LD, scientific=F) -> df1_LD
format(df2_LD, scientific=F) -> df2_LD
format(fval_LD, scientific=F) -> fval_LD
# Improving Figure Literacy for Small P-values
if (pval_LD < 0.0001) {
      pval_LD <- sprintf("%.6e", pval_LD)
    } else {
      format(pval_LD, scientific = FALSE)
    }

# Determines and Demarcates Significant P-Values
  if (as.numeric(pval_LD) < 0.05) {
    pval <- paste0(pval_LD, " *")
  }
      
# Creating Table to Store Unique/Important Coefficients
data.frame(Parameter = c("Df1 (ndf, numerator)","Df2 (ddf, denominator)","F-value",
                         "P-value"), 
           Values =  c(df1_LD, df2_LD, fval_LD, pval_LD)) -> LD_amp_test

# Converting Table into a Graphical Object
tableGrob(LD_amp_test) -> LD_amp_test_grob
```

```{r}
# Plotting the Cosinor Model for LD Rat Data in Grid w/ 
# Table of Values of Interest

# Compute/Compile Fitted Values
(cosMod_LD$fit) -> fitted_values_LD

# Combine Original Data With Fitted Values
LD_Circadian_BodyTemp %>%
  mutate(Fitted = fitted_values_LD$fitted.values) -> LD_plot_data

seq(36, 40, by = 1) -> y_breaks

# Plot LD Cosinor Model Using ggplot2
mod_plot_LD <- ggplot(LD_plot_data, aes(x = ZT)) +
  geom_point(aes(y = BodyTemp, color = "Original Data")) +  # Scatter plot of original data
  geom_smooth(aes(y = Fitted, color = "Cosinor"), size = 1) +  # Fitted line
  xlab("Zeitgeber Time (ZT)")+
  ylab("Body Temperature (degrees C)") +
  ggtitle("LD") +
  theme(plot.title = element_text(hjust = 0.5),
        panel.background = element_rect(fill = "white", color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", color = NA)) +
  scale_color_manual(name = "Legend", values = c("Original Data" = "gray", 
                                                 "Cosinor" = "black")) +
  # Setting y-axis limits
  scale_y_continuous(limits = c(36, 40), breaks = y_breaks) +
  # Setting x-axis limits
  scale_x_continuous(limits = c(0, 25))

# Pairing the Plot of LD Cosinor Model with Table of Important LD Coefficients
#print(mod_plot_LD)

# Printing Tables
#grid.arrange(LD_Results_grob, LD_amp_test_grob, nrow = 1)
```

```{r, fig.height= 5, fig.width= 8}
# Set the working directory to the folder where you want to save the tables
table_dir <- here("Body Temp Combined Figures")
# Create the directory if it does not exist
if (!dir.exists(table_dir)) dir.create(table_dir)

# Define the layout matrix
layout <- rbind(c(1, 1),
                c(2, 3))

# Define the output file path
output_file <- file.path(table_dir, "combined_BodyTemp_LD_fig.pdf")

# Arrange the plot and tables and save to the correct directory
pdf(output_file, width=7, height=6)
grid.arrange(mod_plot_LD, LD_Results_grob, LD_amp_test_grob, 
             layout_matrix = layout) # Adjust heights if needed
dev.off()

```


## Creating and Plotting the Cosinor Body Temp Model for r-LEN Rat Data
```{r}
# Reading Body Temperature Information for r-LEN Rats
readxl::read_excel(path ="../Circadian Disruption ZT Data.xlsx",
                   sheet = "Body Temperature",
                    range ="H1:I71") -> Circadian_BodyTemp_rLEN
```

```{r}
# Cleaning Up Data Column Headers for Easier Translation 
Circadian_BodyTemp_rLEN %>%
  rename(ZT = `Zeitgeber (ZT)`, 
         BodyTemp = `rLEN Body Temperature (degrees C)`
         ) -> rLEN_Circadian_BodyTemp


# Creating Cosinor Model for rLEN Rats
cosinor.lm(BodyTemp ~ time(ZT), period = 24,
           data = rLEN_Circadian_BodyTemp) -> cosMod_rLEN
```

```{r}
# Creating Table of Data Values of Interest for rLEN Rat Model
coef(cosMod_rLEN) -> rLEN_coefficients

# Indexing Unique/Important Coefficients for Table Storage
## Calculate Mesor
rLEN_coefficients[1] -> mesor_rLEN
## Calculate Amplitude
rLEN_coefficients[2] -> amplitude_rLEN
## Calculate Acrophase in Radians
rLEN_coefficients[3] -> acrophase_rLEN
## Calculate Acrophase in Hours
(acrophase_rLEN * 24) / (2 * pi) -> acrophase_rLEN_Hrs
if(acrophase_rLEN_Hrs < 0) {acrophase_rLEN_Hrs <- acrophase_rLEN_Hrs + 24}
# Calculate Bathyphase in Hours
acrophase_rLEN_Hrs + 12 -> bathyphase_rLEN_Hrs
if(bathyphase_rLEN_Hrs >= 24) {
  bathyphase_rLEN_Hrs <- bathyphase_rLEN_Hrs - 24}

# Calculating Number of Observations in Data Set
num_observations_rLEN <- length(cosMod_rLEN$fit$residuals)

# Manually Compute Standard Error
residuals_vec_rLEN <- cosMod_rLEN$fit$residuals

# Check residuals
#if (length(residuals_vec) == 0) {
#  stop("Residuals cannot be computed. The model may not be fit properly.")
#}

# Calculate residual standard error
residual_se_rLEN <- sqrt(sum(residuals_vec_rLEN^2) / (num_observations_rLEN - length(rLEN_coefficients)))

# Print residual standard error for debugging
#print(paste("Residual Standard Error:", residual_se))

# Calculate standard deviation and standard error of acrophase
sd_acrophase_rLEN <- residual_se_rLEN * sqrt((cos(acrophase_rLEN)^2 + sin(acrophase_rLEN)^2) / (amplitude_rLEN^2))
se_acrophase_rLEN <- sd_acrophase_rLEN / sqrt(num_observations_rLEN)

# Calculate standard deviation and standard error of acrophase
sd_acrophase_hrs_rLEN <- (sd_acrophase_rLEN * 24) / (2 * pi)
se_acrophase_hrs_rLEN <- (se_acrophase_rLEN * 24) / (2 * pi)

# Ensure all computed values are single values
sd_acrophase_rLEN <- as.numeric(sd_acrophase_rLEN)
se_acrophase_rLEN <- as.numeric(se_acrophase_rLEN)
sd_acrophase_hrs_rLEN <- as.numeric(sd_acrophase_hrs_rLEN)
se_acrophase_hrs_rLEN <- as.numeric(se_acrophase_hrs_rLEN)

# Creating Table to Store Unique/Important Coefficients
data.frame(Parameter = c("Mesor","Amplitude","Acrophase (Rads)",
                         "Acrophase (Hrs)", "Bathyphase (Hrs)",
                         " Std. Dev. (Rads)"," Std. Error (Rads)",
                         " Std. Dev (Hrs)", " Std. Error (Hrs)"), 
           Values =  c(mesor_rLEN, amplitude_rLEN, 
                       acrophase_rLEN, acrophase_rLEN_Hrs, bathyphase_rLEN_Hrs,
                       sd_acrophase_rLEN, se_acrophase_rLEN, sd_acrophase_hrs_rLEN, 
                       se_acrophase_hrs_rLEN)) -> rLEN_Results

# Converting Table into a Graphical Object
tableGrob(rLEN_Results) -> rLEN_Results_grob
```

```{r}
# Zero-Amplitude Analysis of Cosinor Fit
cosinor.detect(cosMod_rLEN) -> zero_amp_test_rLEN

# Indexing Unique/Important Coefficients for Table Storage
## Calculate Df1
zero_amp_test_rLEN[2] -> df1_rLEN
## Calculate Df2
zero_amp_test_rLEN[3] -> df2_rLEN
## Calculate F Value
zero_amp_test_rLEN[1] -> fval_rLEN
## Calculate p Value
zero_amp_test_rLEN[4] -> pval_rLEN

# Improving Figure Literact for Larger Values
format(df1_rLEN, scientific=F) -> df1_rLEN
format(df2_rLEN, scientific=F) -> df2_rLEN
format(fval_rLEN, scientific=F) -> fval_rLEN
# Improving Figure Literacy for Small P-values
if (pval_rLEN < 0.0001) {
      pval_rLEN <- sprintf("%.6e", pval_rLEN)
    } else {
      format(pval_rLEN, scientific = FALSE)
    }

# Determines and Demarcates Significant P-Values
  if (as.numeric(pval_rLEN) < 0.05) {
    pval_rLEN <- paste0(pval_rLEN, " *")
  }

# Creating Table to Store Unique/Important Coefficients
data.frame(Parameter = c("Df1 (ndf, numerator)","Df2 (ddf, denominator)","F-value",
                         "P-value"), 
           Values =  c(df1_rLEN, df2_rLEN, fval_rLEN, pval_rLEN)) -> rLEN_amp_test

# Converting Table into a Graphical Object
tableGrob(rLEN_amp_test) -> rLEN_amp_test_grob
```


```{r}
# Compute fitted values
(cosMod_rLEN$fit) -> fitted_values_rLEN

# Combine Original Data with fitted values
rLEN_Circadian_BodyTemp %>%
  mutate(Fitted = fitted_values_rLEN$fitted.values) -> rLEN_plot_data

seq(36, 40, by = 1) -> y_breaks

# Plot Using ggplot2
mod_plot_rLEN <- ggplot(rLEN_plot_data, aes(x = ZT, y = BodyTemp)) +
  geom_point(aes(y = BodyTemp, color = "Original Data")) +  # Scatter plot of original data
  geom_smooth(aes(y = Fitted, color = "Cosinor"), size = 1) +  # Fitted line
  xlab("Zeitgeber Time (ZT)")+
  ylab("Body Temperature (degrees C)") +
  ggtitle("rLEN") +
  theme(plot.title = element_text(hjust = 0.5),
        panel.background = element_rect(fill = "white", color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", color = NA)) +
  scale_color_manual(name = "Legend", values = c("Original Data" = "red", "Cosinor" = "black")) + 
 # Setting y-axis limits
  scale_y_continuous(limits = c(36, 40), breaks = y_breaks) +
  # Setting x-axis limits
  scale_x_continuous(limits = c(0, 25))

# Pairing the Plot of rLEN Cosinor Model with Table of 
# Important rLEN Coefficients
#print(mod_plot_rLEN)

# Printing Tables
#grid.arrange(rLEN_Results_grob, rLEN_amp_test_grob, nrow = 1)
```

```{r, fig.height= 5, fig.width= 7}
# Set the working directory to the folder where you want to save the tables
table_dir <- here("Body Temp Combined Figures")
# Create the directory if it does not exist
if (!dir.exists(table_dir)) dir.create(table_dir)

# Define the layout matrix
layout <- rbind(c(1, 1),
                c(2, 3))

# Define the output file path
output_file <- file.path(table_dir, "combined_BodyTemp_rLEN_fig.pdf")

# Arrange the plot and tables and save to the correct directory
pdf(output_file, width=7, height=6)
grid.arrange(mod_plot_rLEN, rLEN_Results_grob, rLEN_amp_test_grob, 
             layout_matrix = layout) # Adjust heights if needed
dev.off()

```
```

